import { HitObject } from '../../beatmap/hitobjects/HitObject';

/**
 * Represents an osu!standard hit object with difficulty calculation values.
 */
export class DifficultyHitObject {
    /**
     * The underlying hitobject.
     */
    readonly object: HitObject;

    /**
     * The aim strain generated by the hitobject.
     */
    aimStrain: number = 0;

    /**
     * The speed strain generated by the hitobject.
     */
    speedStrain: number = 0;

    /**
     * The tap strain generated by the hitobject.
     */
    tapStrain: number = 0;

    /**
     * The finger control strain generated by the hitobject.
     */
    fingerControlStrain: number = 0;

    /**
     * The travel distance of the hitobject.
     */
    travelDistance: number = 0;

    /**
     * The jump distance of the hitobject.
     */
    jumpDistance: number = 0;

    /**
     * The angle created by the hitobject and the previous 2 hitobjects (if present).
     */
    angle: number|null = 0;

    /**
     *  Whether or not the hitobject is considered as singletap.
     */
    isSingle: boolean = false;

    /**
     * The time difference between the hitobject and the previous hitobject (if present).
     */
    deltaTime: number = 0;

    /**
     * The strain time of the hitobject.
     */
    strainTime: number = 0;

    /**
     * The radius of the hitobject.
     */
    radius: number = 0;

    /**
     * The density of this object.
     */
    noteDensity: number = 0;

    constructor(object: HitObject) {
        this.object = object;
    }

    toString(): string {
        return `Strains: [${this.speedStrain.toFixed(2)}, ${this.aimStrain.toFixed(2)}], is_single: ${this.isSingle}`;
    }
}